# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'AllInOne' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for AllInOne
  pod 'SDWebImage'
  pod 'ReachabilitySwift', '~> 4.0'
  pod 'Firebase/Core'
  pod 'Firebase/Auth'
  pod 'Firebase/Database'
  pod 'Fabric'
  pod 'Crashlytics'

  target 'AllInOneTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'AllInOneUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
